### ISSUE TITLE
22/08/26 Future's To-Do

### ISSUE THREAD

**Issue by 1futuro** [DalmoTeam/GOLFLEARN#10]
- [ ] 결제 API 확인 후 샘플 데이터 수정
- [x] 중고거래 게시판에 샘플데이터 추가로 넣기 (25개 이상 되도록)
- [x] 시퀀스값 확인하고 수정
- [x] 댓글 삭제 시 댓글 수 관련 SQL문 확인
- [ ] 테이블 CREATE 잘 되는지 확인(JPA)

**Comment by 1futuro** [comment]
1. 샘플데이터 추가(시퀀스 생성 startwith값 줘서 추가)
2. 메소드 필드 클래스명 논의
3. 개발환경 셋팅
4. entity생성, JPA create 테스트
5. 결제 API 확인 후 결제 테이블, 레슨내역 테이블 샘플데이터 수정
