### ISSUE TITLE
22/09/19 Future's To-Do

### ISSUE THREAD

**Issue by 1futuro** [DalmoTeam/GOLFLEARN#126]
- [x] 샘플 사진 정리
- [ ] 구현 순서 정리
- [ ] 로그인/로그아웃 구동 고치기
