### ISSUE TITLE
22/08/29 Kevin's To-Do

### ISSUE THREAD

**Issue by KevinJo-Keonwoo** [DalmoTeam/GOLFLEARN#23]
- [x] LessonLine repository 완성하기
- [x] LessonLine mapper 완성하기
- [x] repository test method 완성하기
