### ISSUE TITLE
22/08/29 Cokesh's To-Do

### ISSUE THREAD

**Issue by cokesh** [DalmoTeam/GOLFLEARN#25]
## [Refactor] to mybatis
- [x] LessonHistory repo
- [x] LessonHistory control, service
- [x] MainPage 레슨목록 조회 repo
- [x] git project workflow설정을 통해 편리한 backlog관리

**Comment by cokesh** [comment]
**오늘 할일 다했다!**
