### ISSUE TITLE
22/08/31 Future's To-Do

### ISSUE THREAD

**Issue by 1futuro** [DalmoTeam/GOLFLEARN#37]
- [x] 유효성 검사 마무리, 테스트
- [x] Resale Board - create 테스트
- [ ] 결제 API 확인

**Comment by KevinJo-Keonwoo** [comment]
create 테스트라 흥미롭네요

**Comment by cokesh** [comment]
그러게요
하하하
