### ISSUE TITLE
22/08/31 Kevin's To-Do

### ISSUE THREAD

**Issue by KevinJo-Keonwoo** [DalmoTeam/GOLFLEARN#40]
- [x] git branch 만들고 push해보기 
- [x] 서로의 branch 합치고 conflict 해결하기 
- [x] RoundReviewBoard Entity 만들기 
- [x] RoundReviewBoard table create 테스트 해보기

**Comment by cokesh** [comment]
issue close 해주세요!~
