### ISSUE TITLE
22/09/01 1000's To-Do

### ISSUE THREAD

**Issue by myCYWORLD** [DalmoTeam/GOLFLEARN#48]
- [x] ChangePwd 레파지토리 완성
- [x] ChangePwd  서비스 완성
- [x] ChangePwd 컨트롤러 완성
- [x] MSA QnABoard , QnAComment 엔터티 파일 매핑 다시 보기
- [x] MSA 레파지토리 ,,손이라도 대기

**Comment by myCYWORLD** [comment]
레파지토리 테스트까지 진행
