### ISSUE TITLE
22/09/02 1000's To-Do

### ISSUE THREAD

**Issue by myCYWORLD** [DalmoTeam/GOLFLEARN#55]
- [x] QnAComment 레파지토리 완성
- [x] QnAComment 레파지토리  테스트 완성
- [x] QnA Service 시작하기
