### ISSUE TITLE
22/08/25 Future's To-Do

### ISSUE THREAD

**Issue by 1futuro** [DalmoTeam/GOLFLEARN#6]
- [x] SQL 구문 도출
- [x] SQL 구문 JPA 형태로 변경
- [x] 샘플데이터로 도출 구문 확인

**Comment by 1futuro** [comment]
.

**Comment by cokesh** [comment]
Todo 체크 바랍니다~~

**Comment by 1futuro** [comment]
Done
