### ISSUE TITLE
22/09/06 Kevin's To-Do

### ISSUE THREAD

**Issue by KevinJo-Keonwoo** [DalmoTeam/GOLFLEARN#66]
- [x] 양방향 연관관계 적용하기
- [x] Controller serach 메서드 오류 해결하기
- [x] API 내용 DB 적용하기
