### ISSUE TITLE
22/09/07 Jiyeon's To-Do

### ISSUE THREAD

**Issue by JiyeonKimbackend** [DalmoTeam/GOLFLEARN#71]
- [x] 관리자 레슨승인 repo test
- [x] 관리자 레슨승인 service 
- [x]  관리자 레슨승인 controller
