### ISSUE TITLE
22/09/08 Future's To-Do

### ISSUE THREAD

**Issue by 1futuro** [DalmoTeam/GOLFLEARN#75]
- [x] BEM 방법론 숙지
- [ ] 게시판 html 파일 완성
- [x] 게시판 jq 시작
- [x] 텍스트 에디터 구현

**Comment by 1futuro** [comment]
boardlist html 파일, writeboard html 파일 완성
