### ISSUE TITLE
22/09/09 Future's To-Do

### ISSUE THREAD

**Issue by 1futuro** [DalmoTeam/GOLFLEARN#77]
- [ ] boardlist jq 파일 완성
- [ ] boarddetail html 파일 완성
- [x] 회원가입, 로그인 cross origin 해결
- [ ] boarddetail jq 시작

**Comment by 1futuro** [comment]
회원가입 로그인 오류 수정 -> 정상 구동
